/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

public class welcome extends javax.swing.JFrame {

    public welcome() {
        initComponents();
        WELL.setToolTipText("welcome" + login.getuname());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        addUser = new javax.swing.JButton();
        deleteu = new javax.swing.JButton();
        upuser = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        WELL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        WELL1 = new javax.swing.JLabel();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 427));
        setMinimumSize(new java.awt.Dimension(500, 427));
        setPreferredSize(new java.awt.Dimension(500, 427));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(106, 156, 137));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 427));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 427));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 427));

        addUser.setBackground(new java.awt.Color(255, 218, 179));
        addUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addUser.setForeground(new java.awt.Color(102, 102, 102));
        addUser.setText("Add user");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        deleteu.setBackground(new java.awt.Color(255, 218, 179));
        deleteu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        deleteu.setForeground(new java.awt.Color(102, 102, 102));
        deleteu.setText("Delete user");
        deleteu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuActionPerformed(evt);
            }
        });

        upuser.setBackground(new java.awt.Color(255, 218, 179));
        upuser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        upuser.setForeground(new java.awt.Color(102, 102, 102));
        upuser.setText("Update user");
        upuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upuserActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 218, 179));
        logout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(102, 102, 102));
        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        WELL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        WELL.setForeground(new java.awt.Color(255, 255, 255));
        WELL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WELL.setText("WELCOME!");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/logo-white-1.png"))); // NOI18N

        WELL1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        WELL1.setForeground(new java.awt.Color(255, 255, 255));
        WELL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WELL1.setText("Please select an option");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WELL, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUser)
                            .addComponent(deleteu)
                            .addComponent(upuser)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(WELL1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addUser, deleteu, upuser});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout)
                    .addComponent(WELL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(WELL1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addUser)
                .addGap(18, 18, 18)
                .addComponent(upuser)
                .addGap(18, 18, 18)
                .addComponent(deleteu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        dungag dog = new dungag();
        dog.pack();
        dog.setLocationRelativeTo(null);
        dog.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_addUserActionPerformed
//this button used to go to delete window
    private void deleteuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuActionPerformed
        delete dell = new delete();
        dell.setVisible(true);
        dell.pack();
        dell.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_deleteuActionPerformed
//fire to add user window
    private void upuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upuserActionPerformed
        update user = new update();
        user.pack();
        user.setLocationRelativeTo(null);
        this.dispose();
        user.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_upuserActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        login log = new login();
        log.pack();
        log.setLocationRelativeTo(log);
        log.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_logoutActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WELL;
    private javax.swing.JLabel WELL1;
    private javax.swing.JButton addUser;
    private javax.swing.JButton deleteu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton upuser;
    // End of variables declaration//GEN-END:variables
}
